package golosdinner;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rcbgalido
 */
public class Main extends javax.swing.JFrame {

    private static final int SANDGLASS1_MINUTES = 7;
    private static final int SANDGLASS2_MINUTES = 11;
    private static final int EXACT_COOKING_MINUTES = 24;
    private static final int MILLISECONDS_IN_A_SECOND = 1000;
    
    private static final String RESOURCE_LOCATION = "resources/";
    private static final String SANDGLASS_IMAGE_FILENAMES[] = {
        "03_sandglass_00.png", "04_sandglass_01.png", "05_sandglass_02.png", "06_sandglass_03.png",
        "07_sandglass_04.png", "08_sandglass_05.png", "09_sandglass_06.png", "10_sandglass_07.png",
        "11_sandglass_08.png", "12_sandglass_09.png", "13_sandglass_10.png", "14_sandglass_11.png"
    };
    
    private Timer timer;
    private int sandglass1Time, sandglass2Time;
    
    private ImageIcon titleImage;

    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void enableRulesButton() {
        rulesBTN.setEnabled(true);
    }
    
    private void disableRulesButton() {
        rulesBTN.setEnabled(false);
    }
    
    private void enableStartButton() {
        startBTN.setEnabled(true);
    }
    
    private void disableStartButton() {
        startBTN.setEnabled(false);
    }
    
    private void enablePlayButton() {
        playBTN.setEnabled(true);
    }
    
    private void disablePlayButton() {
        playBTN.setEnabled(false);
    }
    
    private void enableTurnSandglassButtons() {
        turnsandglass1BTN.setEnabled(true);
        turnsandglass2BTN.setEnabled(true);
    }
    
    private void disableTurnSandglassButtons() {
        turnsandglass1BTN.setEnabled(false);
        turnsandglass2BTN.setEnabled(false);
    }

    private void disableAllButtons() {
        disableRulesButton();
        disableStartButton();
        disablePlayButton();
        disableTurnSandglassButtons();
    }

    private void checkIfPlayable() {
        if (sandglass1timeTF.getText().equals("0") && sandglass2timeTF.getText().equals("0")) {
            messageTF.setText("turn a sandglass");
            disablePlayButton();
        } else {
            messageTF.setText("turn a sandglass or press on play");
            enablePlayButton();
        }
    }

    private void updateSandglass1() {
        sandglass1upLBL.setIcon(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[sandglass1Time])));
        sandglass1downLBL.setIcon(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[SANDGLASS1_MINUTES - sandglass1Time])));
        sandglass1timeTF.setText("" + sandglass1Time);
    }
    
    private void updateSandglass2() {
        sandglass2upLBL.setIcon(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[sandglass2Time])));
        sandglass2downLBL.setIcon(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[SANDGLASS2_MINUTES - sandglass2Time])));
        sandglass2timeTF.setText("" + sandglass2Time);
    }
    
    private void resetSandglasses() {
        sandglass1Time = 0;
        sandglass2Time = 0;
        updateSandglass1();
        updateSandglass2();
    }
    
    private void stopTimer() {
        timer.cancel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playBTN = new javax.swing.JButton();
        timeTF = new javax.swing.JTextField();
        startBTN = new javax.swing.JButton();
        titleImage=new ImageIcon(getClass().getResource(RESOURCE_LOCATION + "01_title.png"));
        jLabel2 = new javax.swing.JLabel(titleImage);
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        turnsandglass1BTN = new javax.swing.JButton();
        sandglass1upLBL = new javax.swing.JLabel();
        sandglass1downLBL = new javax.swing.JLabel(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[7])));
        jPanel5 = new javax.swing.JPanel();
        turnsandglass2BTN = new javax.swing.JButton();
        sandglass2upLBL = new javax.swing.JLabel();
        sandglass2downLBL = new javax.swing.JLabel(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + SANDGLASS_IMAGE_FILENAMES[11])));
        jPanel3 = new javax.swing.JPanel();
        sandglass1timeTF = new javax.swing.JTextField();
        sandglass2timeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mainLBL = new javax.swing.JLabel(new ImageIcon(getClass().getResource(RESOURCE_LOCATION + "02_main.png")));
        messageTF = new javax.swing.JTextField();
        rulesBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Golo's Dinner");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        playBTN.setText("Play");
        playBTN.setEnabled(false);
        playBTN.setFocusable(false);
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });

        timeTF.setEditable(false);
        timeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeTF.setText("0");
        timeTF.setFocusable(false);

        startBTN.setText("Start");
        startBTN.setFocusable(false);
        startBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("SANDGLASSES");

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        turnsandglass1BTN.setText("Turn");
        turnsandglass1BTN.setEnabled(false);
        turnsandglass1BTN.setFocusable(false);
        turnsandglass1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnsandglass1BTNActionPerformed(evt);
            }
        });

        sandglass1upLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sandglass1downLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sandglass1upLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnsandglass1BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandglass1downLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sandglass1upLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(turnsandglass1BTN)
                .addGap(5, 5, 5)
                .addComponent(sandglass1downLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        turnsandglass2BTN.setText("Turn");
        turnsandglass2BTN.setEnabled(false);
        turnsandglass2BTN.setFocusable(false);
        turnsandglass2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnsandglass2BTNActionPerformed(evt);
            }
        });

        sandglass2upLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sandglass2downLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(4, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turnsandglass2BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sandglass2downLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(sandglass2upLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(sandglass2upLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(turnsandglass2BTN)
                .addGap(5, 5, 5)
                .addComponent(sandglass2downLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sandglass1timeTF.setEditable(false);
        sandglass1timeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sandglass1timeTF.setText("0");
        sandglass1timeTF.setFocusable(false);

        sandglass2timeTF.setEditable(false);
        sandglass2timeTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sandglass2timeTF.setText("0");
        sandglass2timeTF.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sandglass1timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sandglass2timeTF)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sandglass1timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sandglass2timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("TIME ELAPSED");

        mainLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        messageTF.setEditable(false);
        messageTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        messageTF.setFocusable(false);

        rulesBTN.setText("?");
        rulesBTN.setToolTipText("show rules");
        rulesBTN.setFocusable(false);
        rulesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTF)
                            .addComponent(playBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(rulesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mainLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addComponent(messageTF))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rulesBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(messageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        disableAllButtons();
        
        sandglass1Time = Integer.parseInt(sandglass1timeTF.getText());
        sandglass2Time = Integer.parseInt(sandglass2timeTF.getText());
        
        boolean isSandglass1TimeInitiallyZero = (sandglass1Time == 0);
        boolean isSandglass2TimeInitiallyZero = (sandglass2Time == 0);

        messageTF.setText("cooking...");
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                
                int time = Integer.parseInt(timeTF.getText());
                sandglass1Time = Integer.parseInt(sandglass1timeTF.getText() + "");
                sandglass2Time = Integer.parseInt(sandglass2timeTF.getText() + "");
                
                if (time > EXACT_COOKING_MINUTES) { // lose :(
                    stopTimer();
                    enableRulesButton();
                    enableStartButton();
                    messageTF.setText("Game over");
                    JOptionPane.showMessageDialog(null, "Try Again.", "Golo's Dinner", JOptionPane.INFORMATION_MESSAGE);
                } else if ((sandglass1Time == 0 && isSandglass1TimeInitiallyZero == false)
                        || (sandglass2Time == 0 && isSandglass2TimeInitiallyZero == false)) {
                    stopTimer();
                    enableRulesButton();
                    enableStartButton();
                    if (time == EXACT_COOKING_MINUTES) { // win :)
                        messageTF.setText("You Win!!!");
                        JOptionPane.showMessageDialog(null, "Bon Apetit!", "Golo's Dinner", JOptionPane.INFORMATION_MESSAGE);
                    } else { // game continues
                        checkIfPlayable();
                        enableTurnSandglassButtons();
                    }
                } else {
                    
                    if (sandglass1Time != 0) {
                        sandglass1timeTF.setText("" + --sandglass1Time);
                        updateSandglass1();
                    }

                    if (sandglass2Time != 0) {
                        sandglass2timeTF.setText("" + --sandglass2Time);
                        updateSandglass2();
                    }
                    
                    timeTF.setText("" + ++time);
                }
            }

        }, MILLISECONDS_IN_A_SECOND, MILLISECONDS_IN_A_SECOND);
    }//GEN-LAST:event_playBTNActionPerformed

    private void turnsandglass1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnsandglass1BTNActionPerformed
        sandglass1Time = SANDGLASS1_MINUTES - sandglass1Time;
        updateSandglass1();
        checkIfPlayable();
    }//GEN-LAST:event_turnsandglass1BTNActionPerformed

    private void turnsandglass2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnsandglass2BTNActionPerformed
        sandglass2Time = SANDGLASS2_MINUTES - sandglass2Time;
        updateSandglass2();
        checkIfPlayable();
    }//GEN-LAST:event_turnsandglass2BTNActionPerformed

    private void startBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBTNActionPerformed
        resetSandglasses();
        timeTF.setText("0");
        enableTurnSandglassButtons();
        messageTF.setText("turn a sandglass");
        disablePlayButton();
        startBTN.setText("Start Again?");
    }//GEN-LAST:event_startBTNActionPerformed

    private void rulesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBTNActionPerformed
        JOptionPane.showMessageDialog(null, "Please help \'Golo\' cook his dinner.\n"
                + "\'Golo\' has some eggs that needs to be cooked for exactly\n"
                + EXACT_COOKING_MINUTES + " minutes in order to eat them.\n"
                + "There are two sandglasses (one for " + SANDGLASS1_MINUTES + " minutes & the other\n"
                + "for " + SANDGLASS2_MINUTES + " minutes) \'Golo\' can measure time with.", "Golo's Dinner", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rulesBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mainLBL;
    private javax.swing.JTextField messageTF;
    private javax.swing.JButton playBTN;
    private javax.swing.JButton rulesBTN;
    private javax.swing.JLabel sandglass1downLBL;
    private javax.swing.JTextField sandglass1timeTF;
    private javax.swing.JLabel sandglass1upLBL;
    private javax.swing.JLabel sandglass2downLBL;
    private javax.swing.JTextField sandglass2timeTF;
    private javax.swing.JLabel sandglass2upLBL;
    private javax.swing.JButton startBTN;
    private javax.swing.JTextField timeTF;
    private javax.swing.JButton turnsandglass1BTN;
    private javax.swing.JButton turnsandglass2BTN;
    // End of variables declaration//GEN-END:variables
}
